# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vOx2u8XJHWDKI8u4wOD9nArAgkVgLYyY
"""

from sklearn.linear_model import LinearRegression
from src.prepare_data import prepare_data
import matplotlib.pyplot as plt

import pickle
import json

def evaluate():
  model_file = "saved_models" + "/" + "housing_model.h5"
  scores_file = "report" + "/" + "score.json"
  graph_file = "report" + "/" + "prediction.png"


  xtrain, xtest, ytrain, ytest = prepare_data()

  loaded_model = pickle.load(open(model_file, 'rb'))

  y_pred = loaded_model.predict(xtest)


  # Plotting Scatter graph to show the prediction
  # results - 'ytrue' value vs 'y_pred' value
  plt.scatter(ytest, y_pred, c = 'green')
  plt.xlabel("Price: in $1000's")
  plt.ylabel("Predicted value")
  plt.title("True value vs predicted value : Linear Regression")
  plt.savefig(graph_file)


  from sklearn.metrics import mean_squared_error, mean_absolute_error
  mse = mean_squared_error(ytest, y_pred)
  mae = mean_absolute_error(ytest,y_pred)
  print("Mean Square Error : ", mse)
  print("Mean Absolute Error : ", mae)

  with open(scores_file, "w+") as f:
    scores = {
      "MSE": mse,
      "MAE": mae
    }
    json.dump(scores, f, indent=4)