# -*- coding: utf-8 -*-
"""prepare_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E2pIfnWrnNqkwGPFU1zZXsAnQ5rLqT2a
"""

# Importing Libraries
from sklearn.datasets import fetch_california_housing

from sklearn.model_selection import train_test_split
  
# Importing Data
def prepare_data():
  boston = fetch_california_housing()

  # Input Data
  x = boston.data
    
  # Output Data
  y = boston.target
    
    
  # splitting data to training and testing dataset.
  
  #from sklearn.cross_validation import train_test_split
  #the submodule cross_validation is renamed and reprecated to model_selection
  
  return train_test_split(x, y, test_size =0.2, random_state = 0)

xtrain, xtest, ytrain, ytest = prepare_data()

