# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kTOIvVxsNHQ8UQ5xIYa4z-nbcBRbJJOF
"""

from sklearn.linear_model import LinearRegression
from src.prepare_data import prepare_data

import pickle

def train():
  model_file = "saved_models" + "/" + "housing_model.h5"
  print(model_file)
  
  xtrain, xtest, ytrain, ytest = prepare_data()
  regressor = LinearRegression()
  regressor.fit(xtrain, ytrain)

  pickle.dump(regressor, open(model_file, 'wb'))
 
if __name__=="__main__":
    train()
